import networkx

G=networkx.DiGraph()

G.add_node("A1")
G.add_node("A2")
G.add_node("A3")
G.add_node("A4")
G.add_node("B1")
G.add_node("B2")
G.add_node("B3")
G.add_node("B4")
G.add_node("C1")
G.add_node("C2")
G.add_node("C3")
G.add_node("C4")
G.add_node("D1")
G.add_node("D2")
G.add_node("D3")
G.add_node("D4")
G.add_node("E1")
G.add_node("E2")
G.add_node("E3")
G.add_node("E4")
G.add_node("F1")
G.add_node("F2")
G.add_node("F3")
G.add_node("F4")
G.add_node("G1")
G.add_node("G2")
G.add_node("G3")
G.add_node("G4")
G.add_node("H1")
G.add_node("H2")
G.add_node("H3")
G.add_node("H4")

G.add_edge("A2","A1")
G.add_edge("A3","A1")
G.add_edge("A3","A1")
G.add_edge("A4","A2")
G.add_edge("A4","A3")
G.add_edge("A3","A2")

G.add_edge("B4","B3")
G.add_edge("B1","B2")
G.add_edge("B2","B1")
G.add_edge("B4","B2")
G.add_edge("B1","B3")
G.add_edge("B3","B4")
G.add_edge("B4","B3")

G.add_edge("C4","C1")
G.add_edge("C2","C3")
G.add_edge("C3","C1")
G.add_edge("C4","C3")
G.add_edge("C2","C4")
G.add_edge("C4","C2")
G.add_edge("C1","C2")
G.add_edge("C2","C1")

G.add_edge("D4","D2")
G.add_edge("D2","D4")
G.add_edge("D3","D1")
G.add_edge("D2","D1")
G.add_edge("D4","D3")
G.add_edge("D3","D2")
G.add_edge("D4","D3")

G.add_edge("E4","E3")
G.add_edge("E1","E2")
G.add_edge("E2","E1")
G.add_edge("E4","E1")
G.add_edge("E3","E2")
G.add_edge("E3","E1")
G.add_edge("E2","E4")
G.add_edge("E4","E2")

G.add_edge("F4","F2")
G.add_edge("F3","F1")
G.add_edge("F3","F2")
G.add_edge("F1","F4")
G.add_edge("F4","F3")
G.add_edge("F2","F1")

G.add_edge("G4","G1")
G.add_edge("G3","G2")
G.add_edge("G3","G1")
G.add_edge("G4","G2")
G.add_edge("G2","G1")
G.add_edge("G4","G3")

G.add_edge("H1","H2")
G.add_edge("H4","H3")
G.add_edge("H2","H3")
G.add_edge("H3","H2")
G.add_edge("H2","H4")
G.add_edge("H3","H1")
G.add_edge("H4","H1")

G.add_edge("D2","C1")
G.add_edge("B2","A1")
G.add_edge("F2","E1")
G.add_edge("H2","G1")
G.add_edge("A2","B1")
G.add_edge("C2","D1")
G.add_edge("E2","F1")
G.add_edge("G2","H1")
G.add_edge("G2","G1")
G.add_edge("C1","A1")
G.add_edge("G1","E1")
G.add_edge("D1","A2")
G.add_edge("G2","F1")
G.add_edge("G1","C1")
G.add_edge("G2","D1")
G.add_edge("D1","C1")


import matplotlib.pyplot
pos=networkx.spring_layout(G)

networkx.draw_networkx_edges(G,pos)
networkx.draw_networkx_nodes(G,pos)
networkx.draw_networkx_labels(G,pos)

matplotlib.pyplot.show()
pr=networkx.pagerank(G)

networkx.draw_networkx_nodes(G, pos, node_color ='r',node_size=[v*1000 for v in pr.values()])

print(pr)